// V_COMMIT_HASH e804ba5
// V_CURRENT_COMMIT_HASH f6947d1
// Generated by the V compiler

"use strict";

/** @namespace builtin */
const builtin = (function () {
	/**
	 * @function
	 * @param {any} s
	 * @returns {void}
	*/
	function println(s) {
		console.log(s);
	}

	/**
	 * @function
	 * @param {any} s
	 * @returns {void}
	*/
	function print(s) {
		process.stdout.write(s);
	}

	/**
	 * @function
	 * @param {any} s
	 * @returns {void}
	*/
	function eprintln(s) {
		console.error(s);
	}

	/**
	 * @function
	 * @param {any} s
	 * @returns {void}
	*/
	function eprint(s) {
		process.stderr.write(s);
	}

	/**
	 * @function
	 * @param {number} c
	 * @returns {void}
	*/
	function exit(c) {
		process.exit(c);
	}

	/**
	 * @function
	 * @param {string} s
	 * @returns {void}
	*/
	function panic(s) {
		builtin.eprintln(`V panic: ${s}`);
		builtin.exit(1);
	}

	/* module exports */
	return {
		println,
		print,
		eprintln,
		eprint,
		exit,
		panic
	};
})();

/** @namespace foo */
const foo = (function () {
	/**
	 * @function
	 * @returns {void}
	*/
	function hot() {
		if (module.hot) module.hot.accept(() => true)
	}

	/* module exports */
	return {
		hot
	};
})();

/** @namespace main */
const main = (function (foo) {
	/* program entry point */
	(function() {
		builtin.println("Hello, Webpack + V.js !");
		foo.hot();
	})();

	/* module exports */
	return {};
})(foo);


